export const FiftyStates = [
    { name: 'Alabama', abbreviation: 'AL', tax_rate: 0.04 },
    { name: 'Alaska', abbreviation: 'AK', tax_rate: 0.00 },
    { name: 'Arizona', abbreviation: 'AZ', tax_rate: 0.056 },
    { name: 'Arkansas', abbreviation: 'AR', tax_rate: 0.065 },
    { name: 'California', abbreviation: 'CA', tax_rate: 0.0725 },
    { name: 'Colorado', abbreviation: 'CO', tax_rate: 0.029 },
    { name: 'Connecticut', abbreviation: 'CT', tax_rate: 0.0635 },
    { name: 'Delaware', abbreviation: 'DE', tax_rate: 0.00 },
    { name: 'Florida', abbreviation: 'FL', tax_rate: 0.06 },
    { name: 'Georgia', abbreviation: 'GA', tax_rate: 0.04 },
    { name: 'Hawaii', abbreviation: 'HI', tax_rate: 0.04 },
    { name: 'Idaho', abbreviation: 'ID', tax_rate: 0.06 },
    { name: 'Illinois', abbreviation: 'IL', tax_rate: 0.0625 },
    { name: 'Indiana', abbreviation: 'IN', tax_rate: 0.07 },
    { name: 'Iowa', abbreviation: 'IA', tax_rate: 0.06 },
    { name: 'Kansas', abbreviation: 'KS', tax_rate: 0.065 },
    { name: 'Kentucky', abbreviation: 'KY', tax_rate: 0.06 },
    { name: 'Louisiana', abbreviation: 'LA', tax_rate: 0.0445 },
    { name: 'Maine', abbreviation: 'ME', tax_rate: 0.055 },
    { name: 'Maryland', abbreviation: 'MD', tax_rate: 0.06 },
    { name: 'Massachusetts', abbreviation: 'MA', tax_rate: 0.0625 },
    { name: 'Michigan', abbreviation: 'MI', tax_rate: 0.06 },
    { name: 'Minnesota', abbreviation: 'MN', tax_rate: 0.06875 },
    { name: 'Mississippi', abbreviation: 'MS', tax_rate: 0.07 },
    { name: 'Missouri', abbreviation: 'MO', tax_rate: 0.04225 },
    { name: 'Montana', abbreviation: 'MT', tax_rate: 0.00 },
    { name: 'Nebraska', abbreviation: 'NE', tax_rate: 0.055 },
    { name: 'Nevada', abbreviation: 'NV', tax_rate: 0.0685 },
    { name: 'New Hampshire', abbreviation: 'NH', tax_rate: 0.00 },
    { name: 'New Jersey', abbreviation: 'NJ', tax_rate: 0.06625 },
    { name: 'New Mexico', abbreviation: 'NM', tax_rate: 0.05125 },
    { name: 'New York', abbreviation: 'NY', tax_rate: 0.04 },
    { name: 'North Carolina', abbreviation: 'NC', tax_rate: 0.0475 },
    { name: 'North Dakota', abbreviation: 'ND', tax_rate: 0.05 },
    { name: 'Ohio', abbreviation: 'OH', tax_rate: 0.0575 },
    { name: 'Oklahoma', abbreviation: 'OK', tax_rate: 0.045 },
    { name: 'Oregon', abbreviation: 'OR', tax_rate: 0.00 },
    { name: 'Pennsylvania', abbreviation: 'PA', tax_rate: 0.06 },
    { name: 'Rhode Island', abbreviation: 'RI', tax_rate: 0.07 },
    { name: 'South Carolina', abbreviation: 'SC', tax_rate: 0.06 },
    { name: 'South Dakota', abbreviation: 'SD', tax_rate: 0.045 },
    { name: 'Tennessee', abbreviation: 'TN', tax_rate: 0.07 },
    { name: 'Texas', abbreviation: 'TX', tax_rate: 0.0625 },
    { name: 'Utah', abbreviation: 'UT', tax_rate: 0.0595 },
    { name: 'Vermont', abbreviation: 'VT', tax_rate: 0.06 },
    { name: 'Virginia', abbreviation: 'VA', tax_rate: 0.043 },
    { name: 'Washington', abbreviation: 'WA', tax_rate: 0.065 },
    { name: 'West Virginia', abbreviation: 'WV', tax_rate: 0.06 },
    { name: 'Wisconsin', abbreviation: 'WI', tax_rate: 0.05 },
    { name: 'Wyoming', abbreviation: 'WY', tax_rate: 0.04 }
  ];